### ISSUE TITLE
you can use percona query digest mechanism when parse query

### ISSUE THREAD

**Issue by Slach** [SjonHortensius/mysqltop#1]
in your unstable branch
https://github.com/SjonHortensius/mysqltop/blob/64c18bdb93c21234411d60cd610042fad5191d36/mysql-query-log.go#L72

you can use percona query digest mechanism
https://github.com/percona/go-mysql/blob/master/query/query.go#L138

**Comment by SjonHortensius** [comment]
Thanks for the pointer!
